### ISSUE TITLE
Can't migrate 0004 on mysql

### ISSUE THREAD

**Issue by pyMan** [thomst/django-admin-filter#10]
Cannot apply migration number 0004 on mysql backend.

`MySQLdb._exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json NOT NULL' at line 1")`

**Comment by thomst** [comment]
Could you please check the compatibility of your MariaDB-Server with https://github.com/laymonage/django-jsonfield-backport .

**Comment by pyMan** [comment]
Yeah, in debian 8 e 9 mariadb is at 10.0 and 10.1 version, not compatible...

**Comment by thomst** [comment]
> Yeah, in debian 8 e 9 mariadb is at 10.0 and 10.1 version, not compatible...

@pyMan This is really crap. If I would have knew that, I wouldn't have changed the dependencies. Sorry. I will think about it...

**Comment by thomst** [comment]
@pyMan I skipped now the dependecy of django-jsonfield-backport and implemented a very simple JSONField by my own. I also edited the migration 0004. Hope you can update your installation now to 0.6. (Sorry for taking so long. Do this in my free time ;-)

**Comment by pyMan** [comment]
@thomst don't worry and thank you for your work!
