### ISSUE TITLE
Template custom_filter.html missing in pip install

### ISSUE THREAD

**Issue by pyMan** [thomst/django-admin-filter#4]
The installation by pip install (v0.1) doesn't provide the template `custom_filter.html`, that is present with the 0.1 zip release instead.

Plaease, also note that the `form` tag in the template`filter_query.html` is not closed.

**Comment by thomst** [comment]
@pyMan Thanks a lot for pointing me to these bugs. I've fixed the form tag in filter_query and fixed the paths in MANIFEST.in. The next release uploaded to pypi will include the missing templates.

**Comment by thomst** [comment]
This is fixed in version 0.2
